### ISSUE TITLE
Problem Statement

### ISSUE THREAD

**Issue by cer-hunter** [cer-hunter/OAR-CAS741#1]
Problem Statement Submission [Link](https://github.com/cer-hunter/OAR-CAS741/tree/main/docs/ProblemStatementAndGoals)

**Comment by smiths** [comment]
Feedback:

- in the future, make your [link](https://github.com/cer-hunter/OAR-CAS741/blob/main/docs/ProblemStatementAndGoals/ProblemStatement.pdf) directly to the document
- you didn't say anything about the environment. Are you building a program, or a library?  What systems should it run?  Ideally, you want to be portable to multiple systems.

I'm looking forward to seeing how your project turns out.  Should be fun!  :smile:

Your project is approved.
